### ISSUE TITLE
Grunt fails

### ISSUE THREAD

**Issue by CrazyOrange** [AlCalzone/ioBroker.template-ts#14]
I can't get grunt to work following your documentation (I'm on Windows 10 if that should matter).

After running npm install -g grunt-cli
Using grunt rename ... will fail with the following error:

```
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
```

Google suggests to use npm install grunt --save-dev

Now grunt rename will throw this error:
```
Try to rename to "fancyname"
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'C:\devel\SmartHome\ioBroker.template-ts-master/tasks/jscs.js'
Warning: Task "rename" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by JoJ123** [comment]
@CrazyOrange  You solved it anyway? Same issue for me

**Comment by JoJ123** [comment]
@AlCalzone @CrazyOrange I had to add a few dev dependencies to get grunt working. Also the tasks js files, I had to save manually to my template folter.

`"grunt": "^1.0.3",`
`"grunt-cli": "^1.3.1",`
`"grunt-contrib-jshint": "^1.1.0",`
`"grunt-html": "^9.2.0",`
`"grunt-http": "^2.3.1",`
`"grunt-jscs": "^3.0.1",`
`"grunt-http": "^2.3.1",`
`"grunt-replace": "^1.0.1",`

I've created a fork for it:
https://github.com/JoJ123/ioBroker.template-ts

**Comment by AlCalzone** [comment]
This might be because we're trying to move away from grunt and this template is in some intermediate state. Feel free to provide your changes as a PR for the meantime @JoJ123

**Comment by AlCalzone** [comment]
I forgot to change the template from grunt to gulp with the addition of admin 3 support. This repository is going to be discontinued in favor of https://github.com/AlCalzone/create-adapter, so I'm not going to merge this.
