### ISSUE TITLE
Which template is the one to go?

### ISSUE THREAD

**Issue by derchirurg** [AlCalzone/ioBroker.template-ts#15]
Thanks for your typescript template.
Which one should I use? This one or [https://github.com/ioBroker/ioBroker.template-ts](https://github.com/ioBroker/ioBroker.template-ts)?

This one is updated in april, the other one in january.

**Comment by AlCalzone** [comment]
This one should always be the most up-to-date one, since I'm developing the ts-template.

Seems I forgot to update the "official" one under /ioBroker/.

**Comment by AlCalzone** [comment]
I now updated the branches in the "official" repo, closing this... Thanks for the report!
